import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f8f9ff",
        "surface-dim": "#d1dbec",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eef4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dfe9fa",
        "surface-container-highest": "#d9e3f4",
        "on-surface": "#121c28",
        "on-surface-variant": "#444653",
        "inverse-surface": "#27313e",
        "inverse-on-surface": "#eaf1ff",
        outline: "#757684",
        "outline-variant": "#c4c5d5",
        "surface-tint": "#3755c3",
        primary: "#00288e",
        "on-primary": "#ffffff",
        "primary-container": "#1e40af",
        "on-primary-container": "#a8b8ff",
        "inverse-primary": "#b8c4ff",
        secondary: "#006c4a",
        "on-secondary": "#ffffff",
        "secondary-container": "#82f5c1",
        "on-secondary-container": "#00714e",
        tertiary: "#532a00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#743d00",
        "on-tertiary-container": "#ffa85d",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#dde1ff",
        "primary-fixed-dim": "#b8c4ff",
        "on-primary-fixed": "#001453",
        "on-primary-fixed-variant": "#173bab",
        "secondary-fixed": "#85f8c4",
        "secondary-fixed-dim": "#68dba9",
        "on-secondary-fixed": "#002114",
        "on-secondary-fixed-variant": "#005137",
        "tertiary-fixed": "#ffdcc3",
        "tertiary-fixed-dim": "#ffb77d",
        "on-tertiary-fixed": "#2f1500",
        "on-tertiary-fixed-variant": "#6e3900",
        background: "#f8f9ff",
        "on-background": "#121c28",
        "surface-variant": "#d9e3f4",
      },
      fontSize: {
        h1: ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        h2: ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        h4: ["20px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        caption: ["12px", { lineHeight: "16px", letterSpacing: "0em", fontWeight: "400" }],
        "h1-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
        gutter: "24px",
        margin: "32px",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgba(30, 64, 175, 0.05)",
        DEFAULT: "0 4px 6px -1px rgba(30, 64, 175, 0.05)",
        md: "0 4px 6px -1px rgba(30, 64, 175, 0.05), 0 2px 4px -1px rgba(30, 64, 175, 0.03)",
        lg: "0 10px 15px -3px rgba(30, 64, 175, 0.05), 0 4px 6px -2px rgba(30, 64, 175, 0.025)",
        xl: "0 20px 25px -5px rgba(30, 64, 175, 0.08), 0 10px 10px -5px rgba(30, 64, 175, 0.04)",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "var(--font-noto-sans-bengali)", "sans-serif"],
        bengali: ["var(--font-noto-sans-bengali)", "sans-serif"],
      },
      maxWidth: {
        xs: "20rem",
        sm: "24rem",
        md: "28rem",
        lg: "32rem",
        xl: "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem",
      },
    },
  },
  plugins: [],
};

export default config;
