import puppeteer from 'puppeteer-core';
const browser = await puppeteer.launch({ executablePath: '/Users/syed/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing', headless: 'new' });
const page = await browser.newPage();
page.on('console', msg => console.log('PAGE LOG:', msg.text()));
await page.goto('http://localhost:3000/login');
await page.type('input[name="email"]', 'owner@eduflow.bd');
await page.type('input[name="password"]', 'owner123');
await page.click('button[type="submit"]');
await page.waitForNavigation();
console.log('Navigated to', page.url());
await page.click('a[href="/students"]');
await new Promise(r => setTimeout(r, 2000));
console.log('After click, URL is', page.url());
await browser.close();
